name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Configure npm
      run: |
        npm config set shrinkwrap false

    - name: Install dependencies
      run: |
        if [[ "${{ matrix.node-version }}" < "10" ]]; then
          npm rm --silent --save-dev eslint
        fi

        if [[ "${{ matrix.node-version }}" == "0.8" || "${{ matrix.node-version }}" == "0.10" ]]; then
          npm install --save-dev mocha@2.5.3
        elif [[ "${{ matrix.node-version }}" < "4" ]]; then
          npm install --save-dev mocha@3.5.3
        elif [[ "${{ matrix.node-version }}" < "6" ]]; then
          npm install --save-dev mocha@5.2.0
        elif [[ "${{ matrix.node-version }}" < "8" ]]; then
          npm install --save-dev mocha@6.2.2
        elif [[ "${{ matrix.node-version }}" < "10" ]]; then
          npm install --save-dev mocha@7.2.0
        fi

        if [[ "${{ matrix.node-version }}" < "0.10" ]]; then
          npm rm --silent --save-dev nyc
        elif [[ "${{ matrix.node-version }}" < "4" ]]; then
          npm install --save-dev nyc@10.3.2
        elif [[ "${{ matrix.node-version }}" < "6" ]]; then
          npm install --save-dev nyc@11.9.0
        elif [[ "${{ matrix.node-version }}" < "8" ]]; then
          npm install --save-dev nyc@14.1.1
        fi

        if [[ "${{ matrix.node-version }}" < "0.10" ]]; then
          npm install --save-dev supertest@1.1.0
        elif [[ "${{ matrix.node-version }}" < "4" ]]; then
          npm install --save-dev supertest@2.0.0
        elif [[ "${{ matrix.node-version }}" < "6" ]]; then
          npm install --save-dev supertest@3.4.2
        fi

        if [[ -d node_modules ]]; then
          npm prune
          npm rebuild
        fi

    - name: Run tests
      run: |
        if npm -ps ls nyc | grep -q nyc; then
          npm run test-ci
        else
          npm test
        fi

    - name: Run linting
      run: |
        if npm -ps ls eslint | grep -q eslint; then
          npm run lint
        fi

    - name: Upload code coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
