name: CI

on:
  push:
  pull_request:

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 10
        uses: actions/setup-node@v3
        with:
          node-version: '16'




      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgconf-2-4

      - name: Install Cypress
        run: |
          npm install cypress

      - name: Install Cypress binary
        run: |
          ./node_modules/.bin/cypress install

      - name: Run Cypress tests
        run: |
          ./node_modules/.bin/cypress run